# PART 1 - LOAN DATASET

## Loading Dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('loan.csv')

## Describing Dataset

In [ ]:
df.head()

,Unnamed: 0,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income
0,0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,"$5,849.00"
1,1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,"$6,091.00"
2,2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,"$3,000.00"
3,3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,"$4,941.00"
4,4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,"$6,000.00"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         500 non-null    int64
 1   Loan_ID            500 non-null    object
 2   Gender             491 non-null    object
 3   Married            497 non-null    object
 4   Dependents         488 non-null    object
 5   Education          500 non-null    object
 6   Self_Employed      473 non-null    object
 7   ApplicantIncome    500 non-null    int64
 8   CoapplicantIncome  500 non-null    float64
 9   LoanAmount         482 non-null    float64
 10  Loan_Amount_Term   486 non-null    float64
 11  Credit_History     459 non-null    float64
 12  Property_Area      500 non-null    object
 13  Loan_Status        500 non-null    object
 14  Total_Income       500 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 58.7+ KB

In [ ]:
df.describe()

,Unnamed: 0,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,500.000000,500.000000,500.000000,482.000000,486.000000,459.000000
mean,249.500000,5493.644000,1506.307840,144.020747,342.543210,0.843137
std,144.481833,6515.668972,2134.432188,82.344919,63.834977,0.364068
min,0.000000,150.000000,0.000000,17.000000,12.000000,0.000000
25%,124.750000,2874.500000,0.000000,100.000000,360.000000,1.000000
50%,249.500000,3854.000000,1125.500000,126.500000,360.000000,1.000000
75%,374.250000,5764.000000,2253.250000,161.500000,360.000000,1.000000
max,499.000000,81000.000000,20000.000000,700.000000,480.000000,1.000000

In [ ]:
print(f"No of Rows : {df.shape[0]}\nNo. of Columns : {df.shape[1]}")

No of Rows : 500
No. of Columns : 15

In [ ]:
df.columns

Index(['Unnamed: 0', 'Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'Total_Income'],
      dtype='object')

In [ ]:
df.dtypes

Unnamed: 0             int64
Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
Total_Income          object
dtype: object

## Statistical Description for Categorical Variables

In [ ]:
numeric_columns = df.select_dtypes(include=['number']).columns
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns = categorical_columns[categorical_columns != 'Loan_ID']
print("Categorical Columns : ",categorical_columns)
summary_stats = df.groupby(list(categorical_columns))[numeric_columns].describe()
summary_stats

Categorical Columns :  Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Property_Area', 'Loan_Status', 'Total_Income'],
      dtype='object')

                                                                                            Unnamed: 0  \
                                                                                                 count
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00          1.0
                                                                               $2,378.00           1.0
                                                                               $7,541.00           1.0
                                                                   Y           $2,507.00           1.0
                                                                               $3,692.00           1.0
...                                                                                                ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00           1.0
                                                                               $4,611.00           1.0
                                       Yes           Rural         Y           $5,703.00           1.0
                                                     Semiurban     Y           $5,499.00           1.0
                                                     Urban         Y           $7,100.00           1.0

                                                                                                    \
                                                                                              mean
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                                 \
                                                                                            std
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00   NaN
                                                                               $2,378.00    NaN
                                                                               $7,541.00    NaN
                                                                   Y           $2,507.00    NaN
                                                                               $3,692.00    NaN
...                                                                                          ..
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00    NaN
                                                                               $4,611.00    NaN
                                       Yes           Rural         Y           $5,703.00    NaN
                                                     Semiurban     Y           $5,499.00    NaN
                                                     Urban         Y           $7,100.00    NaN

                                                                                                    \
                                                                                               min
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                                    \
                                                                                               25%
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                                    \
                                                                                               50%
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                                    \
                                                                                               75%
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                                    \
                                                                                               max
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    148.0
                                                                               $2,378.00     341.0
                                                                               $7,541.00     298.0
                                                                   Y           $2,507.00     312.0
                                                                               $3,692.00     125.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     202.0
                                                                               $4,611.00     466.0
                                       Yes           Rural         Y           $5,703.00     213.0
                                                     Semiurban     Y           $5,499.00      79.0
                                                     Urban         Y           $7,100.00      68.0

                                                                                            ApplicantIncome  \
                                                                                                      count
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00               1.0
                                                                               $2,378.00                1.0
                                                                               $7,541.00                1.0
                                                                   Y           $2,507.00                1.0
                                                                               $3,692.00                1.0
...                                                                                                     ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00                1.0
                                                                               $4,611.00                1.0
                                       Yes           Rural         Y           $5,703.00                1.0
                                                     Semiurban     Y           $5,499.00                1.0
                                                     Urban         Y           $7,100.00                1.0

                                                                                                      \
                                                                                                mean
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    10000.0
                                                                               $2,378.00      2378.0
                                                                               $7,541.00      5000.0
                                                                   Y           $2,507.00      2507.0
                                                                               $3,692.00      3692.0
...                                                                                              ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00      3992.0
                                                                               $4,611.00      2947.0
                                       Yes           Rural         Y           $5,703.00      5703.0
                                                     Semiurban     Y           $5,499.00      3333.0
                                                     Urban         Y           $7,100.00      7100.0

                                                                                             ...  \
                                                                                             ...
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income  ...
Female No      0          Graduate     No            Rural         N           $11,666.00    ...
                                                                               $2,378.00     ...
                                                                               $7,541.00     ...
                                                                   Y           $2,507.00     ...
                                                                               $3,692.00     ...
...                                                                                          ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     ...
                                                                               $4,611.00     ...
                                       Yes           Rural         Y           $5,703.00     ...
                                                     Semiurban     Y           $5,499.00     ...
                                                     Urban         Y           $7,100.00     ...

                                                                                            Loan_Amount_Term  \
                                                                                                         75%
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00              360.0
                                                                               $2,378.00               360.0
                                                                               $7,541.00               480.0
                                                                   Y           $2,507.00               360.0
                                                                               $3,692.00               360.0
...                                                                                                      ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00               180.0
                                                                               $4,611.00               180.0
                                       Yes           Rural         Y           $5,703.00               360.0
                                                     Semiurban     Y           $5,499.00               360.0
                                                     Urban         Y           $7,100.00                60.0

                                                                                                    \
                                                                                               max
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00    360.0
                                                                               $2,378.00     360.0
                                                                               $7,541.00     480.0
                                                                   Y           $2,507.00     360.0
                                                                               $3,692.00     360.0
...                                                                                            ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00     180.0
                                                                               $4,611.00     180.0
                                       Yes           Rural         Y           $5,703.00     360.0
                                                     Semiurban     Y           $5,499.00     360.0
                                                     Urban         Y           $7,100.00      60.0

                                                                                            Credit_History  \
                                                                                                     count
Gender Married Dependents Education    Self_Employed Property_Area Loan_Status Total_Income
Female No      0          Graduate     No            Rural         N           $11,666.00              1.0
                                                                               $2,378.00               1.0
                                                                               $7,541.00               1.0
                                                                   Y           $2,507.00               1.0
                                                                               $3,692.00               0.0
...                                                                                                    ...
Male   Yes     3+         Not Graduate No            Urban         N           $3,992.00               1.0
                                                                               $4,611.00               1.0
                                       Yes           Rural         Y           $5,703.00               1.0
                                                     Semiurban     Y           $5,499.00               0.0
                                                     Urban         Y           $7,100.00               1.0

                                                                                                  \
                                                                                            mean

### Extracting Categorical Variables

In [ ]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns = list(categorical_columns[categorical_columns != 'Loan_ID'])
print("Categorical Columns : ",categorical_columns)

Categorical Columns :  ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status', 'Total_Income']

### Extracting Numeric Columns

In [ ]:
numeric_columns = df.select_dtypes(include=['number']).columns
print(f"Numeric Columns : {numeric_columns}")

Numeric Columns : Index(['Unnamed: 0', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

### Displaying Stastics for Each Categorical Column

In [ ]:
for i in range(len(categorical_columns)):
    print(f"Statistical Summary for {categorical_columns[i]}\n-------------------------------------------------------------------------------------")
    print(df[[categorical_columns[i]] + list(numeric_columns)].groupby(categorical_columns[i]).describe())

Statistical Summary for Gender
-------------------------------------------------------------------------------------
       Unnamed: 0                                                            \
            count        mean         std   min    25%    50%    75%    max
Gender
Female       91.0  262.340659  135.201514  17.0  140.5  283.0  372.0  495.0
Male        400.0  245.792500  146.126252   0.0  119.5  240.5  373.5  499.0

       ApplicantIncome              ... Loan_Amount_Term         \
                 count        mean  ...              75%    max
Gender                              ...
Female            91.0  4473.10989  ...            360.0  480.0
Male             400.0  5565.52500  ...            360.0  480.0

       Credit_History
                count      mean       std  min  25%  50%  75%  max
Gender
Female           83.0  0.831325  0.376741  0.0  1.0  1.0  1.0  1.0
Male            368.0  0.847826  0.359678  0.0  1.0  1.0  1.0  1.0

[2 rows x 48 columns]
Statistical Summary for Married
-------------------------------------------------------------------------------------
        Unnamed: 0                                                             \
             count        mean         std  min     25%    50%     75%    max
Married
No           175.0  258.085714  140.944183  0.0  133.00  265.0  381.50  499.0
Yes          322.0  244.776398  146.442145  1.0  117.25  237.5  368.75  498.0

        ApplicantIncome               ... Loan_Amount_Term         \
                  count         mean  ...              75%    max
Married                               ...
No                175.0  5091.251429  ...            360.0  480.0
Yes               322.0  5705.689441  ...            360.0  480.0

        Credit_History
                 count      mean       std  min  25%  50%  75%  max
Married
No               164.0  0.835366  0.371986  0.0  1.0  1.0  1.0  1.0
Yes              292.0  0.845890  0.361674  0.0  1.0  1.0  1.0  1.0

[2 rows x 48 columns]
Statistical Summary for Dependents
-------------------------------------------------------------------------------------
           Unnamed: 0                                                      \
                count        mean         std  min     25%    50%     75%
Dependents
0               288.0  245.486111  143.482810  0.0  123.50  243.0  375.50
1                81.0  256.246914  145.816025  1.0  147.00  253.0  368.00
2                79.0  255.177215  156.633883  5.0  115.50  251.0  393.50
3+               40.0  248.950000  138.518156  7.0  132.75  256.0  353.75

                  ApplicantIncome               ... Loan_Amount_Term         \
              max           count         mean  ...              75%    max
Dependents                                      ...
0           499.0           288.0  5035.527778  ...            360.0  480.0
1           498.0            81.0  6008.197531  ...            360.0  480.0
2           488.0            79.0  4620.443038  ...            360.0  360.0
3+          481.0            40.0  9456.850000  ...            360.0  480.0

           Credit_History
                    count      mean       std  min   25%  50%  75%  max
Dependents
0                   264.0  0.856061  0.351695  0.0  1.00  1.0  1.0  1.0
1                    72.0  0.833333  0.375293  0.0  1.00  1.0  1.0  1.0
2                    73.0  0.863014  0.346212  0.0  1.00  1.0  1.0  1.0
3+                   38.0  0.736842  0.446258  0.0  0.25  1.0  1.0  1.0

[4 rows x 48 columns]
Statistical Summary for Education
-------------------------------------------------------------------------------------
             Unnamed: 0                                                    \
                  count        mean         std  min    25%    50%    75%
Education
Graduate          393.0  246.206107  142.131589  0.0  126.0  246.0  367.0
Not Graduate      107.0  261.598131  152.889025  3.0  118.0  253.0  404.5

                    ApplicantIncome               ... Loan_Amount_Term         \
                max           count         mean  ...              75%    max
Education                                         ...
Graduate      499.0           393.0  5990.997455  ...            360.0  480.0
Not Graduate  496.0           107.0  3666.915888  ...            360.0  480.0

             Credit_History
                      count      mean       std  min  25%  50%  75%  max
Education
Graduate              362.0  0.864641  0.342580  0.0  1.0  1.0  1.0  1.0
Not Graduate           97.0  0.762887  0.427522  0.0  1.0  1.0  1.0  1.0

[2 rows x 48 columns]
Statistical Summary for Self_Employed
-------------------------------------------------------------------------------------
              Unnamed: 0                                                     \
                   count        mean         std  min    25%    50%     75%
Self_Employed
No                 407.0  247.977887  143.095827  0.0  124.5  249.0  370.00
Yes                 66.0  262.636364  150.223898  2.0  134.0  253.0  398.75

                     ApplicantIncome               ... Loan_Amount_Term  \
                 max           count         mean  ...              75%
Self_Employed                                      ...
No             499.0           407.0  5198.090909  ...            360.0
Yes            498.0            66.0  6913.181818  ...            360.0

                     Credit_History                                          \
                 max          count      mean       std  min  25%  50%  75%
Self_Employed
No             480.0          378.0  0.835979  0.370786  0.0  1.0  1.0  1.0
Yes            480.0           59.0  0.847458  0.362632  0.0  1.0  1.0  1.0


               max
Self_Employed
No             1.0
Yes            1.0

[2 rows x 48 columns]
Statistical Summary for Property_Area
-------------------------------------------------------------------------------------
              Unnamed: 0                                                     \
                   count        mean         std  min    25%    50%     75%
Property_Area
Rural              141.0  287.106383  130.437654  1.0  176.0  302.0  401.00
Semiurban          188.0  246.505319  143.304227  7.0  115.5  227.5  370.25
Urban              171.0  221.783626  150.722983  0.0   75.5  226.0  357.50

                     ApplicantIncome               ... Loan_Amount_Term  \
                 max           count         mean  ...              75%
Property_Area                                      ...
Rural          499.0           141.0  5900.163121  ...            360.0
Semiurban      498.0           188.0  5371.367021  ...            360.0
Urban          497.0           171.0  5292.877193  ...            360.0

                     Credit_History                                          \
                 max          count      mean       std  min  25%  50%  75%
Property_Area
Rural          480.0          131.0  0.824427  0.381917  0.0  1.0  1.0  1.0
Semiurban      480.0          174.0  0.873563  0.333300  0.0  1.0  1.0  1.0
Urban          480.0          154.0  0.824675  0.381485  0.0  1.0  1.0  1.0


               max
Property_Area
Rural          1.0
Semiurban      1.0
Urban          1.0

[3 rows x 48 columns]
Statistical Summary for Loan_Status
-------------------------------------------------------------------------------------
            Unnamed: 0                                                    \
                 count        mean         std  min    25%    50%    75%
Loan_Status
N                155.0  242.890323  148.351135  1.0  115.0  241.0  371.0
Y                345.0  252.469565  142.828263  0.0  126.0  253.0  375.0

                   ApplicantIncome              ... Loan_Amount_Term         \
               max           count        mean  ...              75%    max
Loan_Status                                     ...
N            499.0           155.0  5773.83871  ...            360.0  480.0
Y            498.0           345.0  5367.75942  ...            360.0  480.0

            Credit_History
                     count      mean       std  min  25%  50%  75%  max
Loan_Status
N                    146.0  0.547945  0.499409  0.0  0.0  1.0  1.0  1.0
Y                    313.0  0.980831  0.137339  0.0  1.0  1.0  1.0  1.0

[2 rows x 48 columns]
Statistical Summary for Total_Income
-------------------------------------------------------------------------------------
             Unnamed: 0                                                  \
                  count   mean        std    min     25%    50%     75%
Total_Income
$1,442.00           1.0   28.0        NaN   28.0   28.00   28.0   28.00
$1,830.00           1.0  338.0        NaN  338.0  338.00  338.0  338.00
$1,950.00           1.0  216.0        NaN  216.0  216.00  216.0  216.00
$1,963.00           1.0  403.0        NaN  403.0  403.00  403.0  403.00
$10,000.00          2.0  264.5  77.074639  210.0  237.25  264.5  291.75
...                 ...    ...        ...    ...     ...    ...     ...
$9,703.00           1.0  246.0        NaN  246.0  246.00  246.0  246.00
$9,734.00           1.0  441.0        NaN  441.0  441.00  441.0  441.00
$9,762.00           1.0  253.0        NaN  253.0  253.00  253.0  253.00
$9,862.00           1.0   89.0        NaN   89.0   89.00   89.0   89.00
$9,993.00           1.0  335.0        NaN  335.0  335.00  335.0  335.00

                    ApplicantIncome           ... Loan_Amount_Term         \
                max           count     mean  ...              75%    max
Total_Income                                  ...
$1,442.00      28.0             1.0   1442.0  ...            360.0  360.0
$1,830.00     338.0             1.0   1830.0  ...            360.0  360.0
$1,950.00     216.0             1.0    150.0  ...            360.0  360.0
$1,963.00     403.0             1.0   1963.0  ...            360.0  360.0
$10,000.00    319.0             2.0  10000.0  ...            360.0  360.0
...             ...             ...      ...  ...              ...    ...
$9,703.00     246.0             1.0   9703.0  ...            360.0  360.0
$9,734.00     441.0             1.0   7901.0  ...            360.0  360.0
$9,762.00     253.0             1.0   2661.0  ...            180.0  180.0
$9,862.00      89.0             1.0   5695.0  ...            360.0  360.0
$9,993.00     335.0             1.0   5503.0  ...              NaN    NaN

             Credit_History
                      count mean  std  min  25%  50%  75%  max
Total_Income
$1,442.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$1,830.00               1.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0
$1,950.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$1,963.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$10,000.00              2.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
...                     ...  ...  ...  ...  ...  ...  ...  ...
$9,703.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$9,734.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$9,762.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$9,862.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0
$9,993.00               1.0  1.0  NaN  1.0  1.0  1.0  1.0  1.0

[457 rows x 48 columns]

# PART 2 - IRIS DATASETS

## Loading Dataset

In [ ]:
df_iris = pd.read_csv('iris.csv')

## Describing Dataset

In [ ]:
df_iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df_iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         500 non-null    int64
 1   Loan_ID            500 non-null    object
 2   Gender             491 non-null    object
 3   Married            497 non-null    object
 4   Dependents         488 non-null    object
 5   Education          500 non-null    object
 6   Self_Employed      473 non-null    object
 7   ApplicantIncome    500 non-null    int64
 8   CoapplicantIncome  500 non-null    float64
 9   LoanAmount         482 non-null    float64
 10  Loan_Amount_Term   486 non-null    float64
 11  Credit_History     459 non-null    float64
 12  Property_Area      500 non-null    object
 13  Loan_Status        500 non-null    object
 14  Total_Income       500 non-null    object
dtypes: float64(4), int64(2), object(9)
memory usage: 58.7+ KB

In [ ]:
df_iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

## Statistical Description for Categorical Variables

### Grouping by Species

In [ ]:
grouped = df_iris.groupby('Species')

### Function to calculate statistics for particular species

In [ ]:
def getStats(x):
  return pd.Series({
      '---' : '------------------------------------------------',
      'count' : x.count(),
      'mean' : x.mean(),
      'median' : x.median(),
      'std' : x.std(),
      'min' : x.min(),
      'max' : x.max(),
      'percentile_25': x.quantile(0.25),
      'percentile_50': x.quantile(0.5),
      'percentile_75': x.quantile(0.75)
  })

### Displaying Statistical Details for each Species

In [ ]:
for i in ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']:
  print(f"Statistical Summary for {i}\n_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_\n")
  print(grouped[i].apply(getStats))

Statistical Summary for SepalLengthCm
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Species
Iris-setosa      ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        5.006
                 median                                                        5.0
                 std                                                       0.35249
                 min                                                           4.3
                 max                                                           5.8
                 percentile_25                                                 4.8
                 percentile_50                                                 5.0
                 percentile_75                                                 5.2
Iris-versicolor  ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        5.936
                 median                                                        5.9
                 std                                                      0.516171
                 min                                                           4.9
                 max                                                           7.0
                 percentile_25                                                 5.6
                 percentile_50                                                 5.9
                 percentile_75                                                 6.3
Iris-virginica   ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        6.588
                 median                                                        6.5
                 std                                                       0.63588
                 min                                                           4.9
                 max                                                           7.9
                 percentile_25                                               6.225
                 percentile_50                                                 6.5
                 percentile_75                                                 6.9
Name: SepalLengthCm, dtype: object
Statistical Summary for SepalWidthCm
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Species
Iris-setosa      ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        3.418
                 median                                                        3.4
                 std                                                      0.381024
                 min                                                           2.3
                 max                                                           4.4
                 percentile_25                                               3.125
                 percentile_50                                                 3.4
                 percentile_75                                               3.675
Iris-versicolor  ---              ------------------------------------------------
                 count                                                          50
                 mean                                                         2.77
                 median                                                        2.8
                 std                                                      0.313798
                 min                                                           2.0
                 max                                                           3.4
                 percentile_25                                               2.525
                 percentile_50                                                 2.8
                 percentile_75                                                 3.0
Iris-virginica   ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        2.974
                 median                                                        3.0
                 std                                                      0.322497
                 min                                                           2.2
                 max                                                           3.8
                 percentile_25                                                 2.8
                 percentile_50                                                 3.0
                 percentile_75                                               3.175
Name: SepalWidthCm, dtype: object
Statistical Summary for PetalLengthCm
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Species
Iris-setosa      ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        1.464
                 median                                                        1.5
                 std                                                      0.173511
                 min                                                           1.0
                 max                                                           1.9
                 percentile_25                                                 1.4
                 percentile_50                                                 1.5
                 percentile_75                                               1.575
Iris-versicolor  ---              ------------------------------------------------
                 count                                                          50
                 mean                                                         4.26
                 median                                                       4.35
                 std                                                      0.469911
                 min                                                           3.0
                 max                                                           5.1
                 percentile_25                                                 4.0
                 percentile_50                                                4.35
                 percentile_75                                                 4.6
Iris-virginica   ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        5.552
                 median                                                       5.55
                 std                                                      0.551895
                 min                                                           4.5
                 max                                                           6.9
                 percentile_25                                                 5.1
                 percentile_50                                                5.55
                 percentile_75                                               5.875
Name: PetalLengthCm, dtype: object
Statistical Summary for PetalWidthCm
_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

Species
Iris-setosa      ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        0.244
                 median                                                        0.2
                 std                                                       0.10721
                 min                                                           0.1
                 max                                                           0.6
                 percentile_25                                                 0.2
                 percentile_50                                                 0.2
                 percentile_75                                                 0.3
Iris-versicolor  ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        1.326
                 median                                                        1.3
                 std                                                      0.197753
                 min                                                           1.0
                 max                                                           1.8
                 percentile_25                                                 1.2
                 percentile_50                                                 1.3
                 percentile_75                                                 1.5
Iris-virginica   ---              ------------------------------------------------
                 count                                                          50
                 mean                                                        2.026
                 median                                                        2.0
                 std                                                       0.27465
                 min                                                           1.4
                 max                                                           2.5
                 percentile_25                                                 1.8
                 percentile_50                                                 2.0
                 percentile_75                                                 2.3
Name: PetalWidthCm, dtype: object